Update acq basic tutorial doc for 1488 and 1489 support
ni/automotive-camera-module-reference pull request #34
Opened 2023-07-13 19:23 UTC by jon-perreault

### What does this Pull Request accomplish?

Update the basic acquisition tutorial doc for 1488 and 1489 hardware support.

2023-07-21 21:56 UTC, hernstrom requested changes

2023-07-21 21:56 UTC, hernstrom commented on docs/tutorials/gettingstartedexample/gse-acq-basic.md
> +A supported interface module and camera on a PXI system running Windows. The table below lists all supported interface modules and supported cameras that have configuration scripts provided with the
Suggest rewording for clarity at a minimum, but see the further comment below for a more comprehensive potential change:

"For cameras not listed in the table below, configuration scripts need to be provided separately."

2023-07-21 21:56 UTC, hernstrom commented on docs/tutorials/gettingstartedexample/gse-acq-basic.md
> +| PXIe-1489 (2 In 2 Out - 96793/96792A SerDes) |                                                                                                                                       |
Why are we listing blank rows in the table?  Is it just to convey that this module doesn't have a script that is provided?

If scripts are coming soon, then blank rows seems ok, but if nota nother option, remove the blank rows and change the last sentence above the table to read:

"For modules & cameras not listed in the table below, configuration scripts need to be provided separately."

2023-07-24 18:26 UTC, jon-perreault commented on docs/tutorials/gettingstartedexample/gse-acq-basic.md
> +A supported interface module and camera on a PXI system running Windows. The table below lists all supported interface modules and supported cameras that have configuration scripts provided with the
Done.

2023-07-24 18:26 UTC, jon-perreault commented on docs/tutorials/gettingstartedexample/gse-acq-basic.md
> +| PXIe-1489 (2 In 2 Out - 96793/96792A SerDes) |                                                                                                                                       |
I added the suggested wording change and removed the blank rows from the table.

2023-07-24 18:58 UTC, hernstrom approved these changes

2023-07-24 19:10 UTC, merged